# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
site_name: IV2py
docs_dir: docs
nav:
  - index.md
use_directory_urls: false
repo_url: https://github.com/iv-project/IV2py
theme:
  name: material
  local: en
  features:
    - navigation.sections
    - content.code.copy
plugins:
  - include-markdown:
      comments: false
      trailing_newlines: false
markdown_extensions:
  - tables
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - attr_list
#  - pymdownx.snippets
  - pymdownx.superfences
#  - pymdownx.critic
#  - pymdownx.caret
#  - pymdownx.keys
#  - pymdownx.mark
#  - pymdownx.tilde
