# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
site_name: IV2py
docs_dir: docs
nav:
  - index.md
  - IO (File Formats):
    - Bam: formats-bam.md
    - Fasta: formats-fasta.md
  - Indices:
    - FM-Index: fmindex.md
  - Complete Examples:
    - Search with an FM-Index: example-search.md
use_directory_urls: false
repo_url: https://github.com/iv-project/IV2py
theme:
  name: material
  local: en
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
plugins:
  - include-markdown:
      comments: false
      trailing_newlines: false
markdown_extensions:
  - tables
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
#  - pymdownx.snippets
  - pymdownx.superfences
#  - pymdownx.critic
#  - pymdownx.caret
#  - pymdownx.keys
#  - pymdownx.mark
#  - pymdownx.tilde
