# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
name: Build Python Binaries

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13]

    steps:
      - uses: actions/checkout@v4
        with:
          path: repo


      - name: Setup Env
        run: |
           echo \"${GITHUB_ACTION}\" \"${GITHUB_REF}\" \"${GITHUB_BASE_REF}\" \"${GITHUB_RUN_NUMBER}\"
           echo "" > env.sh


      - name: Install tools (macos-13)
        if: ${{ matrix.os == 'macos-13' }}
        run: |
           echo 'eval "$(brew shellenv)"' > env.sh
           echo "Setup for " ${{ inputs.compiler }}
           echo "export CXX_STANDARD=cpp20" >> env.sh
           echo "export BUILD_TYPE=Release" >> env.sh
           echo "export CMAKE_CXX_FLAGS=" >> env.sh
           echo "export CMAKE_C_FLAGS=" >> env.sh
           brew update-reset
           brew install --force-bottle --overwrite cmake pkg-config bash

           brew install --force-bottle llvm@17
           brew link -f llvm@17
           echo "export CXX=clang++" >> env.sh
           INSTALL_PREFIX=$(brew --prefix llvm@17)
           echo "export PATH=\"${INSTALL_PREFIX}/bin:$PATH\"" >> env.sh
           echo "export LDFLAGS=\"-L${INSTALL_PREFIX}/lib/c++ -Wl,-rpath,${INSTALL_PREFIX}/lib/c++\"" >> env.sh

      - name: Install tools (win)
        if: ${{ matrix == 'windows-2022' }}
        run: |
          echo "CMAKE_ARGS=-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" >> env.sh

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        if: ${{ matrix.os == 'macos-13' || matrix.os == 'ubuntu-22.04' }}
        run: |
          source env.sh
          cd repo
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          path: ./repo/wheelhouse/*.whl
