# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]

    steps:
      - uses: actions/checkout@v4
        with:
          path: repo

      - name: Install tools
        if: ${{ matrix.os == 'macos-12' }}
        run: |
           echo \"${GITHUB_ACTION}\" \"${GITHUB_REF}\" \"${GITHUB_BASE_REF}\" \"${GITHUB_RUN_NUMBER}\"
           echo 'eval "$(brew shellenv)"' > env.sh
           echo "Setup for " ${{ inputs.compiler }}
           echo "export CXX_STANDARD=cpp20" >> env.sh
           echo "export BUILD_TYPE=Release" >> env.sh
           echo "export CMAKE_CXX_FLAGS=" >> env.sh
           echo "export CMAKE_C_FLAGS=" >> env.sh
           brew update-reset
           brew install --force-bottle --overwrite cmake pkg-config bash

      - name: Setup clang 17
        if: ${{ matrix.os == 'macos-12' }}
        run: |
          source env.sh
          brew install --force-bottle llvm@17
          brew link -f llvm@17
          echo "export CXX=clang++" >> env.sh
          INSTALL_PREFIX=$(brew --prefix llvm@17)
          echo "export PATH=\"${INSTALL_PREFIX}/bin:$PATH\"" >> env.sh
          echo "export LDFLAGS=\"-L${INSTALL_PREFIX}/lib/c++ -Wl,-rpath,${INSTALL_PREFIX}/lib/c++\"" >> env.sh


      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2


      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os == 'windows-2022' }}

      - name: install zlib
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          vcpkg integrate install
          vcpkg install zlib zlib:x64-windows




      - name: Build wheels
        if: ${{ matrix.os == 'macos-12' }}
        run: |
          source env.sh
          cd repo
          python -m cibuildwheel --output-dir wheelhouse

      - name: Build wheels
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          cd repo
          python -m cibuildwheel --output-dir wheelhouse

      - name: Build wheels
        if: ${{ matrix.os == 'windows-2022' }}
        env:
          CMAKE_ARGS: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
        run: |
          cd repo
          python -m cibuildwheel --output-dir wheelhouse


        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v3
        with:
          path: ./repo/wheelhouse/*.whl
